// objects
export const UPDATE_CURRENT_OBJECT = "UPDATE_CURRENT_OBJECT";
export const ADD_OBJECT = "ADD_OBJECT";
export const DROP_OBJECT = "DROP_OBJECT";

//balance
export const CALCULATE_MOMENTUM = "CALCULATE_MOMENTUM";
export const UPDATE_BALANCE = "UPDATE_BALANCE";
